name: "Notion to JSON"
description: "Convert Notion database to JSON"
inputs:
  notion_token:
    description: "Notion token"
    required: true
  notion_database_id:
    description: "Notion database id"
    required: true
  github_token:
    description: "Github token"
    required: true
  commit_branch:
    description: "Commit branch"
    required: false
    default: "main"

runs:
  using: "node20"
  main: "src/index.js"
branding:
    color: "blue"
    icon: "database"
