name: "Notion to JSON"
description: "Convert Notion database to JSON"
inputs:
  notion_token:
    description: "Notion token"
    required: true
    default: ${{ env.NOTION_TOKEN }}
  notion_database_id:
    description: "Notion database id"
    required: true
    default: ${{ env.NOTION_DATABASE_ID }}
  github-token:
    description: "Github token"
    required: true
    default: ${{ github.token }}

runs:
  using: "node20"
  main: "src/index.js"
branding:
    color: "blue"
    icon: "database"
