name: Action Example

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  notion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Notion to JSON
        uses: park-jihoo/notion-action@0.0.2
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


